name: ci
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:
  
jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
       node-version: 20

    - name: Imstall yamllint
      run: sudo npm i -g yaml-lint

    - name: Check yaml
      run: /usr/local/lib/node_modules/yaml-lint/dist/cli.js action.yml

  ci-test:
    needs: yaml-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Test CI
      uses: dabao1955/kernel_build_action@main
      with: 
          kernel-url: https://github.com/Kleinmoretia/android_kernel_oneplus_sm8350
          kernel-dir: msm-5.4
          branch: 13.1
          config: maty_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 13
          aosp-clang-version: r450784d
          python-27: true
          disable-lto: true
          overlayfs: true
          lxc: false
          lxc-patch: false
